### ISSUE TITLE
[syntax] replace .val with method --> .compute()

### ISSUE THREAD

**Issue by youzi** [vigour-io/base#10]
- `.compute()`
- `.parse()`
- `.get()`
- `.calc()`
- `.result()`
- `.val()`
- `.equals()`
- `.value()`

/cc @jimdebeer @shawninder

**Comment by youzi** [comment]
**doodles**
// set a val
`obs.set(something, [event])`
// get a val
`obs.get([input, event])`
// get with path, formerly known as .get 
`obs.grab(path, [set, event])`
// set with path or key
`obs.put(pathOrKey, something, [event])`

**notes**
remove `.retrieve()`

**Comment by youzi** [comment]
**.compute()** vs **.get()**
```js
var obs = new Obs()
obs.compute() === obs
```
```js
var obs = new Obs(1)
obs.compute() === 1
```
```js
var obs = new Obs({
  foo: true
})
obs.compute() === obs
```
```js
var obs = new Obs({
  val:1,
  foo: true
})
obs.compute() === 1
```

**Comment by youzi** [comment]
**.set()**
```js
var obs = new Obs()
obs.set({
  foo:true
}) 
// { foo:true }
obs.set({
  bar:true
}) 
// { foo:true, bar:true }
```

**Comment by youzi** [comment]
**.grab()** vs **.get()**
var obs = new Obs({
  foo:{
    bar:true
  }
}) 
obs.get(['foo', 'bar']) // obs.foo.bar
obs.get(['foo', 'bar', 'val']) // true
obs.get(['foo', 'bar', 'baz']) // undefined
obs.get(['foo', 'bar', 'baz'], 'qux') // obs.foo.bar.qux
obs.get(['foo', 'bar', 'baz', 'val']) // 'qux'
```

**Comment by jimdebeer** [comment]
.compute() is for me still the winner since its more descriptive (versus confusion)

**Comment by jimdebeer** [comment]
replaced with compute
