### ISSUE TITLE
[Components] Naming for components

### ISSUE THREAD

**Issue by youzi** [vigour-io/base#51]
Last call for naming the `components` field and corresponding `type` field.

```js
var bla = new Base({
  components:{ // here we define components/types...
    wut: {
      text: 'smurky'
    }
  },
  wutLikeThing: {
    type: 'wut' // ...which we use here
  }
})
```
To me it's a bit strange that we define "components" which we then use in the "type" field. Should it be either "types" and "type" or "components" and "component"? Or something else completely?

Let's decide fast.

/cc @nfrade @nikoloza @shawninder @jimdebeer

**Comment by nikoloza** [comment]
@youzi I think you're right about that miss of names. But I'd only use inject.

**Comment by nfrade** [comment]
Yeah it should be consistent. Types is shorter to write. But a bit more ambiguous.
They are component types..

**Comment by nfrade** [comment]
I was trying to see if the analogy of data types fitted but I don't think so.

**Comment by nfrade** [comment]
Inject does make sense because seems to be like it works.
But it's not very semantic.
Is there anything going on in components other than just inject them?

**Comment by youzi** [comment]
@nikoloza Using `components` is different then using `inject` which we also have. Inject injects/merges/sets something into the base it's injected on — while `components` define the components/classes/types you get to use within the base (whether on the same level or deeper).
```js
var bla = new Base({
  inject: {
    wut: { // this is merged into bla
      text: 'smurky'
    }
  },
  components:{ // here we define components/types...
    wut: { // ...this is not set on bla, only defines a type...
      text: 'smurky'
    }
  },
  wutLikeThing: {
     type: 'wut' // ...which we use here and...
   },
  somewhere:{
    deeper: {
      anotherWutLikeThing: {
        type: 'wut' // ...which we also use here
      }
    }
  }
})
```

**Comment by nfrade** [comment]
That answers my question.
I like to use _type_. So makes sense _types_, just seems strange. Maybe because I'm already used to _components_.

**Comment by youzi** [comment]
Some quick options I can think of:
```js
var bla = new Base({
  components:{ // here we define components/types...
    wut: {
      text: 'smurky'
    }
  },
  wutLikeThing: {
    type: 'wut' // ...which we use here
  }
})
```
vs
```js
var bla = new Base({
  types:{ // here we define components/types...
    wut: {
      text: 'smurky'
    }
  },
  wutLikeThing: {
    type: 'wut' // ...which we use here
  }
})
```
vs
```js
var bla = new Base({
  components:{ // here we define components/types...
    wut: {
      text: 'smurky'
    }
  },
  wutLikeThing: {
    component: 'wut' // ...which we use here
  }
})
```
vs
```js
var bla = new Base({
  uses:{ // here we define components/types...
    wut: {
      text: 'smurky'
    }
  },
  wutLikeThing: {
    use: 'wut' // ...which we use here
  }
})
```

**Comment by nfrade** [comment]
Components sound like they have more functionality. Like in react. If we're going in that direction we should consider it.
Type is more abstract. 
Uses also sounds interesting.
Needs more thought. If I would have to choose on now I would go with _types_ or leaving it as it is for now.

**Comment by nikoloza** [comment]
@youzi that was clear 👍 I like component, it's bit big to write tho, as we had the same about `Constractor`. we can also call it `module` maybe? Or anyways I'd go with `component`.

**Comment by jimdebeer** [comment]
rename to types + type this is most descriptive of what it is -- see OOP types (`bla.carousel instanceof Carousel`) <--- thats a type right dur

**Comment by jimdebeer** [comment]
we are all just a bit used ot the word components now ;) but yuz and me talked about this for 20 min and types/type really seems to strike the best balance

- most descriptive
- short
