### ISSUE TITLE
remove unnecessary isNode check

### ISSUE THREAD

**Issue by jimdebeer** [vigour-io/base#9]
https://github.com/vigour-io/base/blob/master/lib/iterator/index.js#L7

This has to go away, we have to make sure @DanilloCorvalan adds support for the browser field in vpack. 

See [package.json](https://github.com/vigour-io/base/blob/master/package.json#L29)

----
now we are always adding the regenerator to our source, this is not nessecay

**Comment by ninjatux** [comment]
@DanilloCorvalan assign this back to @shawninder once checked

**Comment by shawninder** [comment]
yes, I can remove the unnecessary `isNode` check from this repo once vpack has support for the package.json `browser` field.

**Comment by DanilloCorvalan** [comment]
@shawninder vpack@1.1.19 adds support for it
please check https://github.com/vigour-io/vpack/tree/master/examples/browser-node

**Comment by shawninder** [comment]
@DanilloCorvalan Almost!

The browserify standard should allow us to do something like:
```json
"browser": {
  "./lib/iterator/": "./lib/iterator/browser.js"
}
```

but vpack is forcing us to use:
```javascript
"browser": {
  "./lib/iterator/index.js": "./lib/iterator/browser.js"
}
```
with a full file path instead of just using the directory and letting it default to index.js

**Comment by DanilloCorvalan** [comment]
@shawninder will take a look at that, it seems to be something with webpack, but there might be a way to make it defaults to index.

**Comment by DanilloCorvalan** [comment]
@shawninder webpack requires you to specify the specific path to the file on `package.json` but in your code you can do like `require('./lib/iterator/')`

**Comment by shawninder** [comment]
hmm, that's not very node... But OK, so be it! I'm going to remove the `isNode` check now and close the issue. Thanks @DanilloCorvalan !
